/**
 * Google reCAPTCHA Enterprise Verification
 * Verifies tokens generated by the frontend
 */

const { RecaptchaEnterpriseServiceClient } = require('@google-cloud/recaptcha-enterprise');

// Configuration
const PROJECT_ID = process.env.GOOGLE_CLOUD_PROJECT || 'campverse-1374';
const RECAPTCHA_SITE_KEY = process.env.RECAPTCHA_SITE_KEY || '6Lds6kUsAAAAANTnwr8PNatSSk5vzWCPGTIF6N5-';

// Score threshold - scores below this are considered potentially bot traffic
const SCORE_THRESHOLD = 0.5;

/**
 * Create an assessment to verify reCAPTCHA token
 * 
 * @param {string} token - The reCAPTCHA token from frontend
 * @param {string} expectedAction - The expected action (e.g., 'LOGIN')
 * @returns {Promise<{valid: boolean, score: number, reasons: string[]}>}
 */
async function verifyRecaptchaToken(token, expectedAction = 'LOGIN') {
    // Skip verification if no token or in development mode
    if (!token || process.env.NODE_ENV === 'development' && !process.env.FORCE_RECAPTCHA) {
        console.log('reCAPTCHA verification skipped (development mode or no token)');
        return { valid: true, score: 1.0, reasons: ['skipped'] };
    }

    try {
        // Create the reCAPTCHA client
        const client = new RecaptchaEnterpriseServiceClient();
        const projectPath = client.projectPath(PROJECT_ID);

        // Build the assessment request
        const request = {
            assessment: {
                event: {
                    token: token,
                    siteKey: RECAPTCHA_SITE_KEY,
                },
            },
            parent: projectPath,
        };

        // Create assessment
        const [response] = await client.createAssessment(request);

        // Close client to free resources
        await client.close();

        // Check if the token is valid
        if (!response.tokenProperties.valid) {
            console.warn(`reCAPTCHA token invalid: ${response.tokenProperties.invalidReason}`);
            return {
                valid: false,
                score: 0,
                reasons: [response.tokenProperties.invalidReason],
            };
        }

        // Check if the expected action matches
        if (response.tokenProperties.action !== expectedAction) {
            console.warn(`reCAPTCHA action mismatch: expected ${expectedAction}, got ${response.tokenProperties.action}`);
            return {
                valid: false,
                score: 0,
                reasons: ['action_mismatch'],
            };
        }

        // Get the risk score and reasons
        const score = response.riskAnalysis.score;
        const reasons = response.riskAnalysis.reasons || [];

        console.log(`reCAPTCHA score: ${score}, reasons: ${reasons.join(', ')}`);

        return {
            valid: score >= SCORE_THRESHOLD,
            score,
            reasons,
        };
    } catch (error) {
        console.error('reCAPTCHA verification error:', error.message);

        // In case of error, allow the request but log it
        // You might want to be stricter in production
        return {
            valid: true, // Allow on error to prevent blocking legitimate users
            score: -1,
            reasons: ['verification_error'],
            error: error.message,
        };
    }
}

/**
 * Express middleware to verify reCAPTCHA
 * Use this on routes you want to protect
 */
function recaptchaMiddleware(action = 'LOGIN') {
    return async (req, res, next) => {
        const token = req.body.recaptchaToken || req.headers['x-recaptcha-token'];

        const result = await verifyRecaptchaToken(token, action);

        if (!result.valid) {
            return res.status(403).json({
                error: 'reCAPTCHA verification failed',
                message: 'Please try again or contact support if the problem persists.',
                reasons: result.reasons,
            });
        }

        // Attach score to request for logging/monitoring
        req.recaptchaScore = result.score;
        next();
    };
}

module.exports = {
    verifyRecaptchaToken,
    recaptchaMiddleware,
    SCORE_THRESHOLD,
};
